let currentCategory='all';
let selectedModalFiles=[];
let currentToolName='';

const AI_FREE_LIMIT=3;
const AI_PLAN_PRICE='₹99/month';
const toolDescriptions={
 'Merge PDF':'Select two or more PDF files and combine them in selection order.',
 'Split PDF':'Select one PDF. Each page is exported into a ZIP file.',
 'Rotate PDF':'Select one PDF. All pages are rotated 90° clockwise.',
 'Compress PDF':'Select one PDF. Pages are rebuilt as optimized JPEGs to reduce file size.',
 'PDF to Word':'Extract selectable PDF text into an editable Word-readable DOC file.',
 'PDF to Text':'Extract selectable text from a PDF into a TXT file.',
 'PDF to JPG':'Render every PDF page as a JPG image inside a ZIP.',
 'JPG to PDF':'Convert JPG, PNG, WebP and other browser-readable images into one PDF.',
 'Watermark PDF':'Add a visible text watermark to every PDF page.',
 'Sign PDF':'Add a typed signature to the first PDF page.',
 'Image Compressor':'Compress JPG, PNG or WebP images in your browser.',
 'AI Document Summary':'Upload a PDF and get an AI-generated summary without entering an API key.'
};
function filterByCategory(cat){currentCategory=cat;document.querySelectorAll('.cat-btn').forEach(b=>b.classList.toggle('active',b.dataset.cat===cat));document.querySelectorAll('.tool-card').forEach(c=>c.style.display=cat==='all'||c.dataset.cat===cat?'':'none');}
function getAiUsage(){const key='fileConvertAiUsage';const month=new Date().toISOString().slice(0,7);let data={month,count:0};try{data=JSON.parse(localStorage.getItem(key)||'null')||data;}catch{}if(data.month!==month)data={month,count:0};return data;}
function getAiRemaining(){return Math.max(0,AI_FREE_LIMIT-getAiUsage().count);}
function recordAiUsage(){const data=getAiUsage();data.count+=1;localStorage.setItem('fileConvertAiUsage',JSON.stringify(data));}
function showAiPlans(){const box=document.getElementById('modal-options');if(!box)return;const remaining=getAiRemaining();box.innerHTML=`<div class="space-y-3"><div class="bg-red-50 border border-red-100 rounded-2xl p-4 text-sm text-slate-700"><div class="flex items-center justify-between gap-3"><div><strong>✨ AI Summary</strong><p class="mt-1">No API key is needed. Your document is processed securely by fileConvert.</p></div><span class="shrink-0 bg-white border rounded-full px-3 py-1 font-bold">${remaining}/${AI_FREE_LIMIT} free</span></div></div><div class="grid md:grid-cols-2 gap-3"><div class="border rounded-2xl p-4 bg-white"><div class="font-black text-lg">Free</div><div class="text-2xl font-black mt-1">₹0</div><ul class="text-sm text-slate-600 mt-3 space-y-1"><li>✓ ${AI_FREE_LIMIT} summaries/month</li><li>✓ Secure AI processing</li><li>✓ Download summary</li></ul></div><div class="border-2 border-red-200 rounded-2xl p-4 bg-red-50/40"><div class="flex justify-between gap-2"><div class="font-black text-lg">Pro</div><span class="text-xs font-bold bg-red-600 text-white px-2 py-1 rounded-full">COMING SOON</span></div><div class="text-2xl font-black mt-1">${AI_PLAN_PRICE}</div><ul class="text-sm text-slate-600 mt-3 space-y-1"><li>✓ 50 summaries/month</li><li>✓ Longer documents</li><li>✓ Priority AI processing</li></ul><button type="button" onclick="showProComingSoon()" class="mt-4 w-full bg-red-600 text-white px-4 py-2.5 rounded-xl font-bold">Upgrade to Pro</button></div></div></div>`;}
function showProComingSoon(){alert('Pro subscriptions are coming soon. Payments are not connected yet, so no charge can be made. Your free AI allowance remains available.');}
function openToolModal(name){currentToolName=name;selectedModalFiles=[];document.getElementById('modal-title').textContent=name;document.getElementById('modal-description').textContent=toolDescriptions[name]||'Select a file to continue.';document.getElementById('tool-modal').classList.remove('hidden');document.getElementById('tool-modal').classList.add('flex');document.getElementById('modal-file-info').classList.add('hidden');document.getElementById('modal-config').classList.add('hidden');document.getElementById('modal-options').innerHTML='';document.getElementById('modal-success').classList.add('hidden');document.getElementById('modal-progress-wrap').classList.add('hidden');document.getElementById('modalFileUpload').value='';const input=document.getElementById('modalFileUpload');input.multiple=['Merge PDF','JPG to PDF'].includes(name);input.accept=name==='Image Compressor'?'image/*':name==='JPG to PDF'?'image/*':'application/pdf';if(name==='AI Document Summary')showAiPlans();if(name==='Watermark PDF')document.getElementById('modal-options').innerHTML='<input id="watermark-text" value="CONFIDENTIAL" class="w-full border rounded-xl p-3" placeholder="Watermark text">';if(name==='Sign PDF')document.getElementById('modal-options').innerHTML='<input id="signature-text" placeholder="Type your name/signature" class="w-full border rounded-xl p-3">';if(name==='Image Compressor')document.getElementById('modal-options').innerHTML='<label class="block font-bold">Quality <span id="quality-value">70%</span></label><input id="image-quality" type="range" min="10" max="95" value="70" class="w-full" oninput="document.getElementById(\'quality-value\').textContent=this.value+\'%\'">';}
function closeToolModal(){document.getElementById('tool-modal').classList.add('hidden');document.getElementById('tool-modal').classList.remove('flex');selectedModalFiles=[];}
function handleModalFileSelect(e){const files=[...e.target.files];if(files.length)loadFiles(files);}
function loadFiles(files){if(currentToolName==='Merge PDF'&&files.length<2)return alert('Select at least two PDF files.');if(currentToolName==='Merge PDF'&&files.some(f=>f.type!=='application/pdf'))return alert('Merge PDF accepts PDF files only.');if(currentToolName==='JPG to PDF'&&files.some(f=>!f.type.startsWith('image/')))return alert('JPG to PDF accepts image files only.');if(currentToolName==='Image Compressor'&&(!files[0]?.type.startsWith('image/')||files.length>1))return alert('Select exactly one image.');if(['AI Document Summary','PDF to Text','PDF to Word','PDF to JPG','Watermark PDF','Sign PDF','Rotate PDF','Split PDF','Compress PDF'].includes(currentToolName)&&files.some(f=>f.type!=='application/pdf'))return alert('This tool accepts PDF files only.');selectedModalFiles=files;document.getElementById('modal-file-info').classList.remove('hidden');document.getElementById('modal-file-name').textContent=files.length===1?files[0].name:files.map(f=>f.name).join(', ');document.getElementById('modal-file-size').textContent=files.map(f=>formatBytes(f.size)).join(' • ');document.getElementById('modal-config').classList.remove('hidden');}
function formatBytes(b){if(!b)return'0 Bytes';const u=['Bytes','KB','MB','GB'];const i=Math.min(Math.floor(Math.log(b)/Math.log(1024)),3);return`${(b/1024**i).toFixed(i?2:0)} ${u[i]}`;}
function setProgress(v,msg){document.getElementById('modal-progress-wrap').classList.remove('hidden');document.getElementById('modal-progress-bar').style.width=Math.max(0,Math.min(100,v))+'%';document.getElementById('modal-status').textContent=msg||'';}
function done(msg='Completed successfully.'){document.getElementById('modal-progress-wrap').classList.add('hidden');document.getElementById('modal-config').classList.add('hidden');const s=document.getElementById('modal-success');s.classList.remove('hidden');s.innerHTML=`<div class="bg-emerald-50 text-emerald-700 p-4 rounded-xl font-bold">✅ ${escapeHtml(msg)}</div>`;}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000);}
async function processFileAction(){if(!selectedModalFiles.length)return alert('Please select a file first.');if(currentToolName==='AI Document Summary'&&getAiRemaining()<=0){showAiPlans();return alert('You have used all 3 free AI summaries this month. Pro subscriptions are coming soon.');}const b=document.getElementById('modal-process-btn');b.disabled=true;const old=b.textContent;b.textContent='PROCESSING…';try{setProgress(10,'Reading file…');const f=selectedModalFiles;switch(currentToolName){case'Merge PDF':await mergePDFs(f);break;case'Split PDF':await splitPDF(f[0]);break;case'Rotate PDF':await rotatePDF(f[0]);break;case'Compress PDF':await compressPDF(f[0]);break;case'PDF to Text':await pdfToText(f[0],false);break;case'PDF to Word':await pdfToText(f[0],true);break;case'PDF to JPG':await pdfToJpg(f[0]);break;case'JPG to PDF':await imagesToPdf(f);break;case'Watermark PDF':await watermarkPDF(f[0]);break;case'Sign PDF':await signPDF(f[0]);break;case'Image Compressor':await compressImageTool(f[0]);break;case'AI Document Summary':await aiSummary(f[0]);break;default:throw new Error('Unknown tool.');}}catch(e){console.error(e);alert(e.message||'Processing failed.');}finally{b.disabled=false;b.textContent=old;}}
async function mergePDFs(files){const out=await PDFLib.PDFDocument.create();for(let i=0;i<files.length;i++){const src=await PDFLib.PDFDocument.load(await files[i].arrayBuffer());const pages=await out.copyPages(src,src.getPageIndices());pages.forEach(p=>out.addPage(p));setProgress(20+70*(i+1)/files.length,'Merging PDFs…');}downloadBlob(new Blob([await out.save({useObjectStreams:true})],{type:'application/pdf'}),'merged.pdf');done('PDFs merged and downloaded.');}
async function splitPDF(file){const src=await PDFLib.PDFDocument.load(await file.arrayBuffer()),zip=new JSZip();for(let i=0;i<src.getPageCount();i++){const d=await PDFLib.PDFDocument.create();const[p]=await d.copyPages(src,[i]);d.addPage(p);zip.file(`page-${i+1}.pdf`,await d.save({useObjectStreams:true}));setProgress(20+70*(i+1)/src.getPageCount(),'Creating pages…');}downloadBlob(await zip.generateAsync({type:'blob'}),'split-pages.zip');done('Split pages downloaded as a ZIP.');}
async function rotatePDF(file){const src=await PDFLib.PDFDocument.load(await file.arrayBuffer());src.getPages().forEach(p=>p.setRotation(PDFLib.degrees((p.getRotation().angle+90)%360)));downloadBlob(new Blob([await src.save({useObjectStreams:true})],{type:'application/pdf'}),'rotated.pdf');done('Rotated PDF downloaded.');}
async function compressPDF(file){const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;const out=await PDFLib.PDFDocument.create();for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i);const viewport=page.getViewport({scale:1.35});const canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;const blob=await new Promise(r=>canvas.toBlob(r,'image/jpeg',0.62));if(!blob)throw new Error('Could not compress PDF page.');const bytes=await blob.arrayBuffer();const img=await out.embedJpg(bytes);const p=out.addPage([img.width,img.height]);p.drawImage(img,{x:0,y:0,width:img.width,height:img.height});setProgress(15+75*i/pdf.numPages,'Compressing PDF…');}const bytes=await out.save({useObjectStreams:true});if(bytes.length>=file.size){done(`The optimized PDF was not smaller (${formatBytes(file.size)} → ${formatBytes(bytes.length)}). The original may already be optimized.`);downloadBlob(new Blob([bytes],{type:'application/pdf'}),'compressed.pdf');return;}downloadBlob(new Blob([bytes],{type:'application/pdf'}),'compressed.pdf');done(`Compressed PDF downloaded (${formatBytes(file.size)} → ${formatBytes(bytes.length)}).`);}
async function pdfToText(file,word){const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;let text='';for(let i=1;i<=pdf.numPages;i++){const c=await(await pdf.getPage(i)).getTextContent();text+=`\n--- Page ${i} ---\n`+c.items.map(x=>x.str).join(' ')+'\n';setProgress(20+70*i/pdf.numPages,'Extracting text…');}if(!text.trim())throw new Error('No selectable text was found. Scanned PDFs need OCR.');if(word){const html=`<html><head><meta charset="utf-8"></head><body><pre style="font-family:Arial;white-space:pre-wrap">${escapeHtml(text)}</pre></body></html>`;downloadBlob(new Blob([html],{type:'application/msword'}),'document.doc');done('Word-readable DOC downloaded.');}else{downloadBlob(new Blob([text],{type:'text/plain;charset=utf-8'}),'document.txt');done('Text file downloaded.');}}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
async function pdfToJpg(file){const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise,zip=new JSZip();for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i),v=p.getViewport({scale:1.5}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.88));if(!blob)throw new Error('Could not render page.');zip.file(`page-${i}.jpg`,blob);setProgress(20+70*i/pdf.numPages,'Rendering pages…');}downloadBlob(await zip.generateAsync({type:'blob'}),'pdf-pages.zip');done('JPG pages downloaded as a ZIP.');}
async function imageToJpegBytes(file,maxDimension=5000,quality=.92){const data=await file.arrayBuffer(),blob=new Blob([data],{type:file.type}),url=URL.createObjectURL(blob);try{const img=await new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error(`Could not read ${file.name}.`));im.src=url;});const scale=Math.min(1,maxDimension/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);const out=await new Promise(r=>c.toBlob(r,'image/jpeg',quality));if(!out)throw new Error('Could not convert image.');return{bytes:await out.arrayBuffer(),width:c.width,height:c.height};}finally{URL.revokeObjectURL(url);}}
async function imagesToPdf(files){const out=await PDFLib.PDFDocument.create();for(let i=0;i<files.length;i++){const{bytes,width,height}=await imageToJpegBytes(files[i]);const img=await out.embedJpg(bytes);const p=out.addPage([width,height]);p.drawImage(img,{x:0,y:0,width,height});setProgress(20+70*(i+1)/files.length,'Building PDF…');}downloadBlob(new Blob([await out.save({useObjectStreams:true})],{type:'application/pdf'}),'images.pdf');done('Images converted to PDF.');}
async function watermarkPDF(file){const src=await PDFLib.PDFDocument.load(await file.arrayBuffer()),font=await src.embedFont(PDFLib.StandardFonts.HelveticaBold),txt=document.getElementById('watermark-text').value.trim()||'CONFIDENTIAL';src.getPages().forEach(p=>{const{width,height}=p.getSize();p.drawText(txt,{x:width*.25,y:height*.5,size:30,font,color:PDFLib.rgb(.8,.1,.1),opacity:.35,rotate:PDFLib.degrees(35)});});downloadBlob(new Blob([await src.save({useObjectStreams:true})],{type:'application/pdf'}),'watermarked.pdf');done('Watermarked PDF downloaded.');}
async function signPDF(file){const src=await PDFLib.PDFDocument.load(await file.arrayBuffer()),font=await src.embedFont(PDFLib.StandardFonts.HelveticaOblique),txt=document.getElementById('signature-text').value.trim()||'Signed',p=src.getPages()[0];p.drawText(txt,{x:50,y:50,size:24,font,color:PDFLib.rgb(0,0,0)});downloadBlob(new Blob([await src.save({useObjectStreams:true})],{type:'application/pdf'}),'signed.pdf');done('Signed PDF downloaded.');}
async function compressImageTool(file){const q=(+document.getElementById('image-quality').value||70)/100;const data=await imageToJpegBytes(file,2400,q);downloadBlob(new Blob([data.bytes],{type:'image/jpeg'}),`${file.name.replace(/\.[^.]+$/,'')}-compressed.jpg`);done(`Compressed ${formatBytes(file.size)} → ${formatBytes(data.bytes.byteLength)}.`);}
async function aiSummary(file){const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;let text='';for(let i=1;i<=Math.min(pdf.numPages,30);i++){const c=await(await pdf.getPage(i)).getTextContent();text+=c.items.map(x=>x.str).join(' ')+'\n';setProgress(15+35*i/Math.min(pdf.numPages,30),'Reading document…');}if(!text.trim())throw new Error('No selectable text found. Scanned PDFs need OCR.');if(text.length>50000)text=text.slice(0,50000);setProgress(60,'Generating AI summary securely…');const res=await fetch('/api/summarize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});let data;try{data=await res.json();}catch{throw new Error('AI service returned an invalid response.');}if(!res.ok)throw new Error(data.error||'Unable to generate the AI summary.');recordAiUsage();const summary=data.summary||'No summary returned.';const box=document.getElementById('modal-success');box.classList.remove('hidden');box.innerHTML=`<div class="bg-slate-50 border rounded-2xl p-5 text-left"><div class="flex items-center justify-between gap-3 mb-3"><h3 class="text-xl font-black">AI Summary</h3><span class="text-xs font-bold bg-red-50 text-red-700 px-3 py-1 rounded-full">${getAiRemaining()} free left</span></div><div class="whitespace-pre-wrap text-slate-700">${escapeHtml(summary)}</div><button id="download-ai-summary" class="mt-4 bg-red-600 text-white px-5 py-3 rounded-xl font-bold">Download summary</button><button type="button" onclick="showAiPlans()" class="mt-3 ml-2 border px-5 py-3 rounded-xl font-bold">View Pro</button></div>`;document.getElementById('download-ai-summary').onclick=()=>downloadBlob(new Blob([summary],{type:'text/plain;charset=utf-8'}),'ai-summary.txt');document.getElementById('modal-config').classList.add('hidden');document.getElementById('modal-progress-wrap').classList.add('hidden');}
function openLoginModal(){document.getElementById('login-modal').classList.remove('hidden');document.getElementById('login-modal').classList.add('flex');}
function closeLoginModal(){document.getElementById('login-modal').classList.add('hidden');document.getElementById('login-modal').classList.remove('flex');}
async function loginWithGoogle(){if(!window.firebaseAuth)return alert('Google sign-in is not initialized. Refresh the page and try again.');const{auth,signInWithPopup,GoogleAuthProvider}=window.firebaseAuth;const button=document.querySelector('#login-modal button[onclick="loginWithGoogle()"]');if(button){button.disabled=true;button.textContent='Connecting to Google…';}try{const provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});await signInWithPopup(auth,provider);closeLoginModal();}catch(e){console.error(e);let m='Google sign-in failed. Please try again.';if(e.code==='auth/popup-closed-by-user')m='The Google sign-in window was closed.';else if(e.code==='auth/popup-blocked')m='Your browser blocked the Google sign-in popup. Allow popups for this site.';else if(e.code==='auth/unauthorized-domain')m='This domain is not authorized in Firebase. Add file-convert-bice.vercel.app in Firebase Authentication → Settings → Authorized domains.';else if(e.code==='auth/operation-not-allowed')m='Google sign-in is disabled in Firebase. Enable Google under Authentication → Sign-in method.';else if(e.code==='auth/network-request-failed')m='Network error. Check your connection.';alert(m);}finally{if(button){button.disabled=false;button.textContent='🌐 Continue with Google';}}}
async function handleLogout(){if(window.firebaseAuth?.signOut)await window.firebaseAuth.signOut(window.firebaseAuth.auth);}
document.addEventListener('DOMContentLoaded',()=>{const dz=document.getElementById('modal-drop-zone'),input=document.getElementById('modalFileUpload');if(dz&&input){dz.addEventListener('click',e=>{if(e.target!==input)input.click();});dz.addEventListener('dragover',e=>{e.preventDefault();dz.classList.add('ring-2','ring-red-400');});dz.addEventListener('dragleave',()=>dz.classList.remove('ring-2','ring-red-400'));dz.addEventListener('drop',e=>{e.preventDefault();dz.classList.remove('ring-2','ring-red-400');loadFiles([...e.dataTransfer.files]);});}if(window.firebaseAuth?.onAuthStateChanged){window.firebaseAuth.onAuthStateChanged(window.firebaseAuth.auth,user=>{const out=document.getElementById('auth-logged-out'),inn=document.getElementById('auth-logged-in'),name=document.getElementById('user-display-name');if(user){out.classList.add('hidden');inn.classList.remove('hidden');inn.classList.add('flex');if(name)name.textContent=user.displayName||user.email||'Account';}else{out.classList.remove('hidden');inn.classList.add('hidden');inn.classList.remove('flex');}});}});
